apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-server-deployment
spec:
  selector:
    matchLabels:
      app: hello-server
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: hello-server:v1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-server
  ports:
  - port: 8080
    name: http
  type: NodePort


#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: gateway
#  annotations:
#    kubernetes.io/ingress.class: "istio"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /world
#        backend:
#          serviceName: hello-server
#          servicePort: 8080