apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-server-deployment
spec:
  selector:
    matchLabels:
      app: hello-server
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: hello-server:v1
        ports:
        - containerPort: 8080