apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: time-server-deployment
spec:
  selector:
    matchLabels:
      app: time-server
  replicas: 2
  template:
    metadata:
      labels:
        app: time-server
    spec:
      containers:
      - name: time-server
        image: time-server:v1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: time-service
spec:
  selector:
    app: time-server
  ports:
  - port: 8080
    name: http